### ISSUE TITLE
changing the position of Donate button for the alignment.

### ISSUE THREAD

**Issue by aashimgarg** [Catalyst-CSE/Catalyst#22]
**Description of the enhancement**
changing the position of Donate button for the alignment.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by codetheorem** [comment]
exactly at which position do you want the donate button.

**Comment by Amankumar29** [comment]
i think position is correct just the little bit alignment problem is there,i think which is due to design in the left side.
we can do:
increase the height of design
or
decrease the font size of punch line
your views @anubhavsingh16 @aashimgarg

**Comment by Amankumar29** [comment]
@anubhavsingh16 @codetheorem any views?

**Comment by codetheorem** [comment]
we can now align it correctly because our punch line has been changed so it will be done in the next PR.

**Comment by anubhavsingh16** [comment]
Okk @codetheorem

**Comment by anubhavsingh16** [comment]
For alignment @Amankumar29 idea is right.
