### ISSUE TITLE
Add footer 

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-CSE/Catalyst#4]
## Description: 
Add footer with all the description given in wireframe. And make them responsive.

## Mocks
![issue2](https://user-images.githubusercontent.com/47811606/82594803-4746bb80-9bc2-11ea-8775-91f6cf0a523d.png)

### Update [Required]
- [x] [Add footer logo]
- [x] [Policy, terms and condition, news latter, contact us button]
- [x] [Add dyanimc quotation]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by codetheorem** [comment]
I want to work on this issue.

**Comment by anubhavsingh16** [comment]
ok cool
